export  default  {
    USER_REGISTER_START: 'USER_REGISTER_START',
    USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',
    USER_REGISTER_RECEIVE: 'USER_REGISTER_RECEIVE',
    USER_LOGOUT_START: 'USER_LOGOUT_START',
    USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
    USER_LOGOUT_RECEIVE: 'USER_LOGOUT_RECEIVE'
}